### ISSUE TITLE
libgit2_features() always returns FALSE for HTTPS

### ISSUE THREAD

**Issue by jdblischak** [ropensci/git2r#319]
I am able to use the HTTPS protocol to push and pull using git2r on Ubuntu (17.10), macOS (10.10.5), and Windows (10), but `libgit2_features()` always returns `FALSE`. Furthermore, during the package installation, git2r reports that HTTPS is enabled. I don't have the same problem with SSH, i.e. `libgit2_features()` returns `TRUE` if I have LibSSH2, and `FALSE` otherwise.

Below is a reproducible example with the Docker image rocker/tidyverse. Please let me know if there are any additional details that would be useful to provide.

```
$ sudo docker run --rm -ti rocker/tidyverse bash
Rscript -e 'devtools::install_github("ropensci/git2r")'
# ...
#  ----- Results of the git2r package configure -----
#
#    OpenSSL to talk over HTTPS...........: yes
#    LibSSH2 to enable the SSH transport..: yes
#
#  --------------------------------------------------
# ...
Rscript -e 'packageVersion("git2r")'
# [1] ‘0.21.0.9000’
Rscript -e 'git2r::libgit2_features()'
# $threads
# [1] FALSE
# 
# $https
# [1] FALSE
# 
# $ssh
# [1] TRUE
Rscript -e 'sessionInfo()'
# R version 3.4.3 (2017-11-30)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Debian GNU/Linux 9 (stretch)
# 
# Matrix products: default
# BLAS: /usr/lib/openblas-base/libblas.so.3
# LAPACK: /usr/lib/libopenblasp-r0.2.19.so
# 
# locale:
# [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
# [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
# [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C             
# [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
# [9] LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  base     
# 
# loaded via a namespace (and not attached):
# [1] compiler_3.4.3
```

**Comment by stewid** [comment]
Thanks for reporting this. Fixed in f52b06c6f63793d58daea0e20c35ae82ccee62de

**Comment by jdblischak** [comment]
@stewid Great! Thanks for the quick response. I confirmed that the fix works on all 3 operating systems.

**Comment by englianhu** [comment]
> I am able to use the HTTPS protocol to push and pull using git2r on Ubuntu (17.10), macOS (10.10.5), and Windows (10), but `libgit2_features()` always returns `FALSE`. Furthermore, during the package installation, git2r reports that HTTPS is enabled. **I don't have the same problem with SSH, i.e. `libgit2_features()` returns `TRUE` if I have LibSSH2, and `FALSE` otherwise**.
> ...
> ...
> ...

```diff
+:~$ sudo apt-get install libssh2-1 libssh2-1-dev -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssh2-1 is already the newest version (1.8.0-2.1build1).
libssh2-1-dev is already the newest version (1.8.0-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
+:~$ sudo apt-get install libssh2* -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libssh2-1' for glob 'libssh2*'
Note, selecting 'libssh2-php' for glob 'libssh2*'
Note, selecting 'libssh2-1-dev' for glob 'libssh2*'
libssh2-1 is already the newest version (1.8.0-2.1build1).
libssh2-1-dev is already the newest version (1.8.0-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```
Installed through terminal.

```r
> require('git2r')
Loading required package: git2r
> libgit2_features()
$threads
[1] FALSE

$https
[1] TRUE

$ssh
[1] FALSE
```
`ssh` still shows `FALSE`, relevant https://github.com/ropensci/git2r/issues/140#issuecomment-101410628 & https://github.com/r-lib/devtools/issues/796#issuecomment-390695559.

**Comment by jdblischak** [comment]
@englianhu Please open a new Issue. This old issue was about HTTPS support, which was already fixed. Your issue is with SSH support, not HTTPS. In your new issue, please include the output from running `install.packages("git2r")`. It contains diagnostic messages about its attempts to find the required system packages to support SSH. Also please include the output of `sesssionInfo()`.
